version: "3.8"

services:

    # Development container. Runs in debug mode and live-reloading on ./config/config.yml file update.
  develop:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      DEBUG: "true"
      SERVING_PORT: ":8808"
    volumes:
      - .:/anonym
    working_dir: /anonym
    ports:
      - "8808:8808"  # Opened ports
    depends_on:
      - anonym-data
      - redis
    command: bash -c "go mod download && make serve"

    # Production container.
  prod:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      SERVING_PORT: ":8808"
    working_dir: /anonym
    ports:
      - "8808:8808"  # Opened ports
    depends_on:
      - anonym-data
      - redis
    command: ./anonym

  anonym-data:
    image: mongo:4.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=testdb
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save ''

