version: "3.8"

services:

    # Development container. Runs in debug mode and live-reloading on ./config/config.yml file update.
  develop:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/anonym
    working_dir: /anonym
    ports:
      - "8808:8808"  # Opened ports
    depends_on:
      - anonym-data
      - redis
    command: bash -c "go mod download && make serve"

    # Production container.
  prod:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    working_dir: /anonym
    ports:
      - "8808:8808"
      - "40000:40000"
    depends_on:
      - anonym-data
      - redis
    command: ./anonym

# You can use Mongo or any other databases that supporting by GORM (MySQL, Postgress, SQLite,...)
#  anonym-data:
#    image: mongo:4.4
#    environment:
#      - MONGO_DATA_DIR=/data/db
#      - MONGO_LOG_DIR=/dev/null
#      - MONGODB_DATABASE=testdb
#    volumes:
#      - ./.data/db:/data/db
#    ports:
#      - 27017:27017
#    command: mongod --logpath=/dev/null # --quiet

  anonym-data:
    image: mysql:8.0
    restart: unless-stopped
#    command: --init-file /data/init.sql --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=19pzda12
      - MYSQL_DATABASE=anonym
      - MYSQL_USER=inspector
      - MYSQL_PASSWORD=GDS64okey
    volumes:
      - ./.data/mysql:/data/mysql
#      - ./.data/init.sql:/data/init.sql
#    ports:
#      - 3306:3306    #needs only for development purpose

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save ''

