server:
  name: "Anonymous security server"
  version: "0.0.1.27b"
  host:
  port: 8808
database:
  system: "mongo"
  uri: "mongodb://anonym-data:27017"
  name: "anonymous"
redis:
  server: "redis:6379"
  password: ""
  DB: 0
token:
  lifespan: 14400