server:
  name: "Anonymous security server"
  version: "0.0.2.00b"
  host:
  port: 8808
database:
  type: "mysql"
  uri: "inspector:GDS64okey@tcp(anonym-data:3306)/anonym?charset=utf8mb4&parseTime=True&loc=Local"
  name: "anonymous"
redis:
  server: "redis:6379"
  password: ""
  DB: 0
token:
  lifespan: 14400